# 電子商務基本概念 {#fundamentals}

## 電子商務的定義

經濟部商業司：｢電子商務是指任何經由電子化形式所進行的商業交易行動。」

簡單來說，電子商務 (Electronic Commerce, e-commerce) 可以用下面的方面定義， $電子商務 = 網路 + 商務$，也就是在網路上進行的商業活動。詳細來說，電子商務是指利用網際網路進行購買、銷售或交換產品與服務 (Kalakota & Whinston, 1997)。

商務包含三個構面：

1. 產品(包括電腦軟體、數位內容或服務)

2. 銷售流程：產品的行銷、搜尋、訂購、付款、運送、售後服務等

3. 交易場合

三個構面可能是實體的，也可能是數位的，從產品、行銷流程到交易場合三者皆為實體，到三者皆為數位，共可以分為八種模式。舉例而言，

- 顧客到Cosco裡買一件衣服，這裡三個構面的屬性都是實體的。

- 到shopee.com裡買一件衣服，雖然產品仍是實體的，但交易場合是網路上的數位商店，因此屬於數位的，銷售流程中也有大部分屬於數位的形式，包括行銷、搜尋、訂購與付款，甚至售後服務。

- 顧客到電影院購票看電影，顧客觀賞的產品是數位的電影，但是顧客在電影院售票口購票進場，交易場合是實體的，銷售流程也是實體。

以下請分析產品、行銷流程到仲介者等三個構面的屬性：

- 顧客在網站上購票參加演唱會

- 顧客訂閱KKBox的月費會員，在網路上收聽歌曲

廣義上來說，只要三個構面中，有任何一個涉及數位化，便可以稱為電子商務。

## 電子商務經營模式的分類

**B2C (企業對消費者)電子商務模式**
B2C是指企業直接在網路上銷售商品或服務給一般消費者，其特點在便利的消費過程與充足的資訊。例如Amazon.com、PChome線上購物、Lativ等等。

**B2B (企業對消費者)電子商務模式**
B2B是指在電子商務交易中，組成份子為企業集其相關夥伴，也就是企業與企業直接在網路上與另一企業進行交易活動，例如[Salesforce](https://www.salesforce.com/tw/)。

## 電子商務的七流

從e化的角度，電子商務可從七個流(flow)來討論：1)商流、2)物流、3)金流、4)資訊流、5)人才流、6)服務流、7)設計流。前四流為主要流，其餘為次要流。

1. 商流：**資產所有權的轉移**，亦即商品由製造商、物流中心、零售商、到消費者的所有權轉移過程。

2. 物流：**商品的運送傳遞**，亦即製造商如何將商品送到消費者手中之商品流動的過程。注意實體商品與數位商品的區別。

3. 金流：**錢或帳的流通過程**，重點主要在付款系統與安全機制。

4. 資訊流：為達上述三項流動而造成的**資訊交換**。

5. 人才流：培訓兼具網際網路暨商務能力的人才。

6. 服務流：將多種分散、斷斷續續的線上、線下服務順暢地連接成連續的服務。

7. 設計流：針對B2B的協同商務設計，強調企業間設計資訊的分享與共用；針對B2C的商務網站設計，強調顧客使用介面的友善與客製化。

## 電子商務的重要經濟法則

1. 梅特卡菲定律 (Metcalfe's Law)：網路的效用與使用者數的平方成正比。

2. 網路外部性 (Network Externalities)：一項產品對個別使用者的價值取決於總使用人數。

3. 距離經濟理論：所謂的｢距離」包括各種空間、時間、關係、資源等需求的差距。若能利用網際網路的特性與優勢，解決某些距離問題，就能找到商機和盈利點。
空間距離：[Uber Eats](https://www.ubereats.com/zh-TW/)
時間距離：[FunNow](https://www.myfunnow.com/)
關係距離：[Eatgether](https://www.eatgether.com/)
資源距離：[Hahow 好學校](https://hahow.in/)


## 討論 {-}
開放銀行 (open banking)的定義是指銀行在取得消費者同意後，透過應用程式介面（API）與其他銀行或是第三方金融業者的合作，藉由取得消費者資料，提供更加個人化的金融服務。[這則新聞](https://www.bnext.com.tw/article/54471/ibm-dbs-open-banking)便是運用開放銀行的概念進行電子商務的例子。

1. 請先從電子商務經營模式的分類討論該銀行的定位。

2. 再從電子商務的重要經濟法則進行分析該銀行的策略。

3. 最後分析電子商務過程中的七流。


## 作業 {-}

1. 找出一個電子商務平台，討論其產品、銷售流程、仲介者等構面各為實體或數位？ 

2. 舉出上述電子商務平台相反之構面的另一個電子商務平台，例如原先的電子商務平台為數位產品、數位銷售流程、實體仲介者(eg. 到台灣大哥大門市選購通信費率)，此時便舉一個實體產品、實體銷售流程、數位仲介者(eg. 房仲業者的房仲網)的例子。

3. 請以上面兩個作業的電子商務平台之一，搜尋相關新聞，討論如何應用電子商務經營模式的分類、電子商務的重要經濟法則以及電子商務過程中的七流進行分析該企業的策略。
