# 電子商務網站架設 {#website-building}

網路虛擬商店是電子商務中最重要的環節，本課程說明網路虛擬商店的種類。在各種網路虛擬商店中，最能夠依據企業本身需求設置相關網頁與功能的方式是專屬電子商務網站，因此本課程也將說明專屬電子商務網站的建置步驟與目前各種產業中提供的各種方式。

## 網路虛擬商店
網路虛擬商店是企業在網路上販售與交易商品的通路，通常需要行銷、商品搜尋、訂單、會員、購物車等等商流功能，並且提供金流、物流等協助。

目前常見的網路虛擬商店建置有以下幾種：

1. 使用網拍機制：運用大型網站提供的拍賣機制。

2. 參加商城、商店街：加入大型網站設立的聯合商城、商店街等網路市集，借助大型網站的知名度。例如：PChome購物中心、momo摩天商城等。

3. 租賃電子商務網站：租賃現成的電子商務網站，可依據本身產品的風格屬性建立網站的外觀介面，節省自行開發程式與管理網站所需的心力。例如[Shopline全球智慧開店平台](https://shopline.tw)

4. 建置專屬電子商務網站：自行架設企業專用的電子商務網站，可以依據企業本身特殊需求量身打造。

## 專屬電子商務網站建置步驟

1. 註冊網址：每個主機對應到一個IP位址，例如世新大學官網的伺服器主機為192.192.159.98。由於這個四個位元組的IP位址對一般使用者來說並不容易記憶，所以透過DNS (Domain Name Service)的服務，以另一個較容易記憶的字串--網域名稱(Domain Name)，俗稱網址，方便使用者記憶與。例如世新大學官網的網域名稱為www.shu.edu.tw。在網路上，網域名稱的最後一個部分是國別碼，例如tw是臺灣、jp和kr分別是日本和韓國。如果不是國別碼，則是主機的所屬機構，例如com為公司、gov是政府機構、org為非政府組織、edu是教育單位。註冊網域可以到中華電信、亞太、遠傳等網路服務提供商(Internet Service Provider)處申請。

2. 在網路上設置伺服器主機或申請網路空間，來架設網站。詳情可參見下一節。

3. 將註冊的網域名稱設定在伺服器主機或網路空間上。

4. 在伺服器主機或網路空間上安裝電子商務網站的程式與上傳網頁。

## 專屬電子商務網站建置的方式
建置專屬電子商務網站需要在網路上建立主機或一個網路空間，有專屬的網址與伺服器名稱，以便使用者可以搜尋到與使用這個電子商務網站。目前專屬電子商務網站的建置有以下幾種方式：

1. 自行架設網站伺服器：用戶自行購置管理主機軟硬體、申請固定IP位址與頻寬，並且需要具有網路管理專業知識的從業人員。

2. 主機代管：用戶自行購置與管理主機軟硬體，並向主機代管業者承租機櫃位置及網路頻寬，主機代管業者則只幫忙「開機、關機、重啟主機」等，不會處理主機內系統的問題。

3. 虛擬主機：虛擬主機業者使用特殊的軟硬體技術，把一台的伺服器主機分成多台*虛擬*的主機，每一台虛擬主機都具有獨立IP位址，具有完整的伺服器功能。虛擬主機之間完全獨立，並可由用戶自行管理。

4. 申請網路空間：由業者管理與維護伺服器，提供用戶架設網站。

## 討論 {-}

在專屬電子商務網站的各種建置方法中，具有不同的功能性，也各自需要不同的成本與資源，適合不同規模的企業。接下來，請討論不同建置方法所需的成本、資源以及達成的功能性。

## 作業 {-}

請根據你心目中構想的電子商務，擬訂一套電子商務網站的架設方案，列出採購清單(包含廠商、規格與價格)，並說明該方案的適用性與所需成本。
