# 電子商務付費系統與安全機制 {#payment_system}

整個電子商務的交易流程是環繞在消費者、商店、金融單位與物流業者等四個主要部分間的商流、金流、物流與資訊流，其中金流便是消費者、商店與金融單位間有關金錢往來與交易的流通過程。電子商務的付費系統較傳統模式方便，但其安全也同樣令人擔憂，如何建立穩定安全的金流環境是電子商務的重要基石。

## 電子商務付費模式

目前常見的電子商務付費模式可分為非線上付費與線上付費兩大模式。

### 非線上付費

非線上付費包括傳統的劃撥轉帳、ATM轉帳、傳真刷卡以及貨到付款和超商代碼轉帳。其中貨到付款需要郵局或便利商店與物流業者的配合；超商代碼轉帳則會在消費者購買後產生一組繳費代碼，利用繳費代碼在超商的ibon貨family port上，完成付費，然後取得服務。

非線上付費的問題包括；

- 離線處理比較不方便。

- 需要在網路上銀行帳號、信用卡號碼與個人身分等機密資料，較不安全。

- 信用卡只能再發卡銀行特約經銷商中交易流通，非特約經銷商則無法進行交易。

- 信用卡或支票需要一定的身分審核，並非人人都可達到合格標準而擁有帳戶。

- 小額交易不符成本考量。

### 線上付費

線上付費包括線上刷卡、電子現金、WebATM、電子票據、小額付款機制、第三方支付與虛擬貨幣。

- 線上刷卡：利用網站提供刷卡付費機制。消費者在網站上輸入信用卡號與基本資料，商店將資料送到信用卡收單銀行請求授權，只要經過許可，商店便可向銀行取得貨款。以信用卡為基礎的電子付款系統必須能夠確保客戶資料、信用卡號碼、交易內容等資料在網路上傳輸的安全，並且需要有公正的認證機構(例如信用卡發卡組織)對所有交易的個體發給身分認證，讓交易雙方可以在線上驗證對方身分，及利用認證上的公開金鑰進行資料交換，進行安全的信用卡付款交易。

- 電子現金：模擬一般現金付費模式，消費者先將貨幣數值轉換成加密的數位資料，使用電子現金付款時，再將數位資料轉換為金額。目前常見的電子現金付款模式包括智慧卡與電子錢包。

- WebATM：晶片金融卡的網路收單服務，只要將晶片金融卡插入讀卡機，連結電腦上網到WebATM，就可以轉帳支付。

- 電子票據：以電子方式製成的票據，在支付及兌現的過程中使用個人及銀行的數位憑證。電子票據包括電子支票、電子本票和電子匯票。

- 小額付款機制：電信業者與網路服務業者提供小額付款平台，消費者只要輸入手機號碼與密碼，利用行動電話的個人化及安全機制，便可進行小額付款，費用會列入下期的電信帳單內收取。

- 第三方支付：在交易過程中，除了買賣雙方外，透過第三方來代收與代付款項。當買方選購商品後，利用第三方支付平台提供的帳戶，進行貨款支付。當貨款支付後，由第三方支付平台通知賣方貨款到款，要求發或。買方收到貨品，檢驗無誤後，即可通知第三方支付平台付款給賣方。著名的第三方支付，如PayPal與支付寶。

- 虛擬貨幣：一種無法律約束，由開發者發行與管控，在特定虛擬社群成員中接受和使用的數位貨幣。虛擬貨幣可以在某些虛擬社群中，像實體貨幣一樣運作的交換媒介，但不具備實體貨幣的所有屬性。比特幣(Bitcoin)是不依靠某一個中央貨幣機構發行的全球通用加密虛擬貨幣，由特定演算法通過大量計算(稱為挖礦)產生。比特幣不僅是一種資產，也是一種支付方式，透過私鑰作為數位簽章，允許個人直接支付給他人，與現金相同，不需經過如銀行等第三方機構，從而避免了高手續費、繁瑣流程以及受監管性的問題，任何用戶只要擁有可連線網際網路的數位裝置皆可使用。

## 行動支付

通過手機對於消費商品或服務進行帳務支付的一種方式，換句話說，便是可以直接用手機刷卡、轉帳、使用優惠券。

### NFC行動支付

### QR Code支付

## 電子商務交易安全機制

### SSL

### SET
