# 電子商務經營策略 {#strategies}

策略規畫 (strategic planning) 是企業或管理者思考策略方案、設計行動計畫的過程。台大國際企業系教授湯明哲指出，透過策略規畫可以使公司的目標和工作順序更清楚，也可以讓企業經理人對未來發展有一致的看法。在競爭激烈愈來愈激烈的商場上，經理人必須要有策略規畫的能力，透過理性而系統化的分析和思維方式，完整掌握企業的經營環境，從中推衍出足以克敵致勝的策略構想、化為具體的執行方案，進而協助企業因應各種經營挑戰。

策略規畫包含4個步驟：

1. 釐清企業的願景與使命
2. 分析內外狀況
3. 形成策略與目標
4. 計畫和評估

## 釐清企業的願景與使命 　

策略的起點來自於企業的**願景**和**使命**。企業受到外部環境之機會與威脅的影響，進行規劃電子商務策略。電子商務策略規劃的第一步，必須先決定其願景與使命。

願景與使命提供了企業成長和發展的方向。缺乏了成長和發展的方向，策略就會變成「不知為何而戰」。

### 願景

願景是指**企業存在的價值**，也就是是企業全體員工長期努力追求的理想。

願景對企業來說，是一個現實的、可信的、有吸引力的未來。例如：百視達（Blockbuster）將他們的願景定義為「成為全球領先的娛樂器材租借公司。」

願景也可以不僅描述企業本身想要成為的未來，也可以描繪將來的理想人類社會。致力於為非洲貧困地區的初生寶寶提供簡易式保溫箱，以提高嬰兒生存率的公益組織「擁抱」，他們在首頁上明確的說明了自己的願景：「我們相信，每一位婦女和兒童都應擁有健康生活的平等機會。」

### 使命

使命是企業為**實現願景所應從事的任務**，讓企業內外的相關人員了解企業的方向和自己的作用，以凝聚共識心、激發承諾感。以百視達的使命為例，在定義其願景為「成為全球領先的娛樂器材租借公司。」之後，百視達提出他們的使命為「提供卓越的服務、優質的選擇、便利的條件和理想的價值」。

「擁抱」的使命則是，「為那些世界上最脆弱的人群，提供創新的解決方案，以推動母嬰健康的提升。」

## 分析內外狀況 　

策略不是憑空而來的，往往是受到許多內外因素的影響，例如法令改變、出現競爭者、技術研發突破等等。所以，策略規畫者在釐清使命和目標之後，還必須偵察和評估**企業所處的外在環境**以及**企業自身的資源條件**，才能了解自己所處的地位和所能發揮的優勢，而做為選擇、擬定策略的前提。

### 外在環境分析

外在環境分析主要包括總體環境分析、產業環境分析以及顧客分析：

1. 總體環境分析：主要在了解企業所處大環境的變動和趨勢，包括了「政治法律」、「經濟」、「社會文化」、「科技」(PEST)4大層面。

2. 產業環境分析：產業環境分析主要是鎖定在企業所競爭的市場上，可劃分為3個部分：
- 結構：了解產業的現有狀況。
- 演進：分析產業的發展趨勢。
- 競爭：界定競爭者並研究其作為。

3. 顧客分析：顧客分析的主要目的，在於尋找並探究市場各種可能的區隔方式，以及顧客的購買動機，以找出未被滿足的顧客需要。對於以B2C為主的企業而言，顧客分析尤其重要。

### 內在條件分析

除了外在環境的分析，策略規畫者還要確認企業內部的組織狀態和所擁有的能力，才能設法以本身的條件配合環境的趨勢，發展企業的策略。

威斯康辛大學麥迪遜分校商學院教授佛米沙諾（Roger Formisano）認為內在條件分析的層面包含「結構」「資源」「文化」這3個部分：

1. 結構：策略規畫者必須仔細檢視組織的組織形態、活動、流程等結構。

2. 資源：企業的資源是指組織有形或無形的資產、技術或知識，包括財務資源、人力資源、技術資源等等。透過對資源的分析，可以了解企業的優勢所在。

3. 文化：企業的文化主要是指對營運方式的共識、創業的精神、管理風格、對風險的容忍度。這些因素在從事新事業或進行購併等策略時，就會造成影響。

## 形成策略與目標

在做完分析檢視後，策略規畫者就要開始運用所蒐集到的資訊和結果，進行策略的思考和選擇。

### 策略的思考和選擇
一般來講，多數策略管理的學者都建議可以利用SWOT分析的方式，將由內部條件分析所評估的優勢(Strengths)、劣勢(Weaknesses)，以及外部環境分析所發現的機會(Opportunities)、威脅(Threats)，做一個綜合性的評量，來幫助策略的研擬和選擇。

在完成SWOT分析後，可以將組織內部的優、劣勢與外部環境的機會、威脅配對，並形成4大基本策略，即根據優勢利用機會(SO)的成長型策略、根據優勢監視威脅(ST)的穩定型策略、利用機會改進劣勢(WO)的扭轉型策略和消除劣勢和威脅(WT)的防禦型策略。

### 目標

目標是**企業想要達成的具體指標**。透過目標的建立，對策略將有明確的指引作用，並且可以了解執行的成果。目標的訂定是根據企業的願景、使命、過去績效以及和標竿企業的比較等等研究的結果，並且其描述必須清楚、準確、可達成、可衡量而具有時效的，例如「半年內達到市占率前三名」等等。

## 計畫和評估

擬定相關策略之後，策略規畫者還要發展出擴及各相關單位的實際計畫和任務，才能確實地將策略執行出來。因為策略決定了，並不代表部屬就知道該做什麼，所以在這一階段，策略規畫者和管理當局需要**將整體的策略展開為各單位的目標**，並訂出一系列的具體計畫，以讓相關執行者了解策略要如何實施，以及各自應擔負的行動與責任。，各單位的目標則必須和公司目標互相配合、互相彌補和銜接，以支持整體目標的達成。單位目標確定之後，接著就是擬出達成這些目標的單位策略。

例如：

- 行銷部門可能的策略有：目標市場、產品組合策略、定價策略、推廣與銷售策略、配銷策略。
- 生產作業部門可能的策略有：設施、自製或外購、供應廠商。
- 人力資源部門可能的策略有：雇用、晉升、薪資福利。
- 財務部門可能的策略有：融資權益策略、資金來源、財務預測。

至於策略的評估(evaluation)，是指**將策略的實施結果和預期目標相比較**，並將所得到的資訊回饋給策略規畫者的過程。持續的評估可以讓策略規畫者了解策略的執行狀態，如果環境有變化即可適時做出回應或矯正。

## 如何擬定策略計畫書？

透過詳細完整的策略規畫程序，擬定未來的策略方針和內容後，接下來就是將策略規畫的過程以及結果化為書面文件，具體呈現策略計畫，讓員工感受企業方向，激勵工作動機，並有控制衡量的依據，而有助於策略的溝通、執行和評估。

策略計畫書的格式如下：

1. 願景描述：簡潔、清楚地表述未來希望將公司經營成什麼樣的企業，並指出企業的獨特性。

2. 使命描述：描述未來的發展重點，包括公司事業與資源的本質，以及公司的理念和核心價值，以為公司發展提出一個具體的輪廓。

3. 企業及其環境：針對企業的經營環境做一個廣泛的瀏覽和探討，以了解影響公司經營的各種動態關鍵因素（如經濟發展、產業趨勢、科技突破等等）。

4. 企業的優勢和劣勢：分析公司的資源和能力，及其相對於競爭者的優劣勢所在。

5. 企業的成長策略與目標：指出公司實際的發展方向和原則，同時也把焦點集中在更具體的預期結果。

6. 單位目標與策略：各單位的目標必須和公司目標互相配合、互相彌補和銜接，以支持整體目標的達成。

7. 評估：落實目標管理。

## 討論 {-}

[Disney正式公布自家的OTT影視平台：Disney+](https://www.bnext.com.tw/article/53174/disney+-ott-strategy)，請根據本文分析Disney+的SWOT。

## 作業 {-}

試著找出一個可能創業的電子商務領域，然後寫出公司的願景與使命。
