# 電子商務消費者行為 {#consumer-behaviors}

消費者行為硏究個人，團體或組織為滿足其需求，在選擇和使用產品或服務時的經驗或想法。消費者行為試圖了解**消費的決策過程**，例如情緒如何影響購買行為。消費者行為的研究涉及購買行為的所有方面，從購買前的活動到購買後的消費、評價和處理活動。它還涉及直接或間接參與購買決定和消費活動的所有人，包括品牌影響者和意見領袖。

**購買路徑**指潛在消費者在消費行為中經歷的各階段。消費者的購買路徑並非全然不可預測，它是重複發生、有跡可循的。基本上，企業可以根據行銷活動的過程和消費者購買活動的心理演變等，來推論顧客的購買路徑，藉此導出一套具有高度可操作性，且可提升行銷效率的步驟。學界對購買路徑頗有興趣，多年也不斷推導、修正，並發表多種路徑模式。

## 傳統消費者行為

### AIDA

AIDA是最早形成的消費者行為模式。AIDA的每個字母表示潛在消費者從接觸商品資訊（如廣告﹑型錄……等）開始﹐一直到完成商品消費行為（購買）的幾個階段﹕

- A (Attention)：經由廣告的**刺激**，吸引潛在消費者開始注意某產品或品牌。(文章的曝光量，PageViews)
- I (Interest)：閱聽人注意到廣告所傳達的訊息之後，激起消費者的興趣和認同。通常興趣的產生是由於廣告提供某種**利益**(Benefit)或**功能性**(Functionality)所致。(文章的留言、分享等互動數)
- D (Desire)：消費者對廣告主所提供的利益如果有**想要據為己有**的感覺，就會激發消費者購買該產品的望。興趣與慾望有時只是一線之隔，如果掌握住消費者發生興趣的一剎那，使之轉化為慾望，廣告就成功了大半。(進入網路商店，加入購物車中)
- A (Action)，消費者採取購買行動。(實際購買數)

### AIDMA

AIDMA比AIDA模式在激發消費者購買該產品的慾望後，多了一個M (Memory)，意指消費者提到該產品會立即聯想到某些記憶或印象的階段。

AIDMA的過程是指在消費者從看到廣告到發生購物行為之間的心理過程。首先消費者**注意**到該廣告。認識商品後，發現自己對這個商品或廣告**感到興趣**而閱讀下去，而通常這個興趣產生是因為消費者認為這個商品能提供了某種改善生活的利益(Benefit)。因此出現了**想買來一試的欲望**。然後在某個時機與場合下，**記起該廣告的內容**，最後產生了**購買行為**。這種因廣告發生功效而引導消費者產生的心理變化，就稱為AIDMA法則。

### 4A架構

洛克(Derek Rucker)根據AIDA模型，將興趣和欲望兩個階段簡化成態度(Attitude)階段，再加上一個新階段：再次行動(act again)，改稱為**4A架構**。在這個新架構裡，目標在追蹤顧客保留率(customer retention)，將重複購買視為顧客忠誠度的強烈指標。

## 電子商務消費者行為

### AISAS
隨著網路日漸普及，消費行為也跟著轉變，因此2004年日本電通公司提出更符合時代的消費者行為模式AISAS。

- A (Attention)，吸引潛在消費者開始注意某產品或品牌。
- I (Interest)，激起消費者的興趣和認同。
- S (Search)，消費者主動搜尋產品。
- A (Action)，做完一系列的評比以後消費者決定購買該產品。
- S (Share)，將使用產品後的心得發至社群平台，讓其他有意願的消費者可以參考。


AISAS模式和過去最大的差別在於兩個S：消費者可以主動「蒐集資料」(search)，提升對商品了解的速度；使用商品後，也可能會在網路上分享(share)，引發其他消費者的好奇，甚至好的評價會促使其他消費者上網搜尋，並採取購買行動。在AISAS法則中，充分體現了目前消費者在購物前後對於網路上他人意見與經驗看重的重要性，更把消費行為與使用心得視為是生活的一部分，重視購物的『使用體驗』，而不是一味地向用戶進行單向的理念灌輸。

因應這個購買行為的轉變，企業可以從3個方向思考，帶動新的商業模式：

1. 將商品資訊數位化放到網路上，讓消費者可以搜尋到商品。

2. 建立會員制度，透過消費者的購物記錄，了解消費者的喜好，對個別消費者進行客製化行銷。

3. 讓消費者在網站上發表意見，提出對商品更好的建議，或是參與商品的推廣，並給予正面回饋，創造口碑行銷。

### 5A架構

5A架構，包括認知(Aware)、訴求(Appeal)、詢問(Ask)、行動(Act)和倡導(Advocate)。

- 認知階段：企業廣告和來自其他顧客的口碑是品牌知名度主要的來源。另外，之前有使用過品牌的顧客，比較容易想起和認得品牌。

- 訴求階段：顧客認知到幾個品牌之後，會將接觸到的訊息經過處理，創造短期記憶或擴大成長期記憶，結果只對少數幾個品牌印象深刻。

- 詢問階段：由於好奇心驅使，顧客會對那些吸引他們的品牌，從親友、媒體或上網搜尋產品評價，甚至直接向客服中心、銷售人員詢問，。他們也可能會比價，甚至在店裡試用產品，蒐集更多資訊。在詢問階段，顧客體驗路徑從個人轉為社群。顧客會根據和其他人的對話內容做出決定，品牌訴求必須獲得社群認可，才能繼續出現在顧客體驗路徑上。

- 行動階段：在購買某個品牌之後，顧客會透過消費和使用，以及售後服務進一步與品牌互動。品牌必須確保顧客完全擁有自主權，而且擁有正面和記憶深刻的使用體驗。當顧客有問題和抱怨時，品牌必須密切注意，並確保問題獲得解決。

- 倡導階段：隨著時間經過，顧客可能會發展出對品牌的強烈忠誠度，這會反映在顧客保留率、重複購買，以及向其他人主動推薦或捍衛自己喜愛的品牌上。

## 討論 {-}

網路上有許多利用消費者行為模式分析廣告案例的文章，例如：[世大運行銷](https://www.smartm.com.tw/article/34313831cea3)和[化妝品品牌行銷](https://www.marketersgo.com/creativity/201806/dg5-skii-bareskinproject-aisas/)，請問你是否可以想到其他的例子？

## 作業 {-}

以上週電子商務的創業案例，提出你們將如何利用兩種消費者行為模式？
