# 網路行銷基本概念{#internet-marketing-introduction}

## 行銷的定義
美國市場行銷協會對行銷的定義是：行銷是創造、溝通與傳送價值給顧客，及經營顧客關係，以便讓組織與其利益關係人(stakeholder)受益的一種組織功能與程序。Kolter認為行銷是一種社會性及管理性的過程，個人與群體可經由此過程，彼此創造及交換產品與價值，以滿足其需求與慾望。根據以上的定義，企業要必須從**目標市場需求**和**市場行銷環境**的特點出發，根據企業的資源和優勢，綜合運用各種手段，形成統一的策略，使之發揮整體效應，爭取消費者與企業雙方的最佳效果。

行銷從洞悉消費者與企業的需求、選擇目標市場、發展產品定位開始；從設計產品、定價、選擇販售的通路、直到銷售推廣，每個步驟都「籠罩在行銷的影子底下」。

## 網路行銷的定義
網路行銷即是**運用網路資源與工具**，依據企業的品牌調性、產品和目標客群制定各種適合的行銷策略，推送給有潛力購買的顧客。甚至讓顧客參與整個企劃流程，顧客一方面可與企業溝通，另一方面也可和其他消費者交換意見，以雙向甚至多向的溝通形式，維持並促進顧客關係，來達成銷售目的。網路行銷包含數位廣告投放、社群平台、email電子報行銷等方式。

網路行銷將特定的行銷訊息傳遞給特定的顧客，包括透過豐富的資料庫內容分析、辨識線上消費者的行為模式與偏好等。

- 在產品市場上，網路行銷以服務性、金融或資訊產品為主。
- 在通路方面，採用虛擬通路，倉儲與庫存等需求低，因此租金成本低。
- 在推廣方面，提供兼顧完整性與迅速的銷售資訊。
- 在價格方面，由於降低中間商與通路的需求以及具有價格彈性，所以遠較傳統行銷便宜。

### 網路行銷的轉變

- 由產品導向行銷到**顧客導向**行銷：在網路時代，顧客面對眾多產品提供者，於是更在意自己的想法與意見是否受到重視。

- 從在乎價格到重視**價值**：對許多消費者而言，價格已經不是太大的問題，為了產品帶來的價值，願意辛苦工作，花費大筆金額購買。根據尼爾森數據(https://www.brain.com.tw/news/articlecontent?ID=48018#3HvzOcpp)，八成五的台灣消費者在選購商品時重視商品本身（口味／功能／用途），甚至超越價格和品牌，此外，也有過半消費者在意產品的原料／成份／材質。

- 傳統通路到**虛實整合**的多元通路

- 從單向推廣到**雙向溝通**與顧客共創價值

[Mary Meeker在2019年年度趨勢報告中提到](https://www.brain.com.tw/news/articlecontent?ID=48018#sKQMLtk7)，有效果且有效率的行銷方程式應該是商品＋快樂消費者＋口碑推薦。

- 商品： 消費者購買前，商品本身的口味／功能／用途是最主要的考慮因素，價格其次，所以品牌必須先優化自己的商品。

- 快樂消費者： 品牌擁有堅強的產品力，需要讓更多潛在消費者了解、體驗。品牌通常會運用遊戲化行銷增加與消費者的互動，讓消費者有好心情、好體驗與好感受，逐漸建立一批忠實顧客並逐漸增加銷售額。

口碑推薦： 忠誠顧客會推薦自己的親朋好友使用、或者在社群上分享，達到口碑擴散，為企業帶來更多試用體驗，達到正向的循環。口碑的威力就在於常常讓消費者一股腦地跟風，創造意想不到的爆款商品。

## 社群行銷

六個簡單的步驟，可以幫助中小企業減省時間和精力，提升社群行銷的生產力和競爭力。 1.確認社群行銷是整體行銷的一部分：現今許多已經在使用社群媒體的企業，很少企業能擬定明確的社群行銷戰略。社群行銷營運的目標應該明確，例如，一個月內辦三檔活動，提高品牌知名度50 %，其中包括按讚、貼文、評論或分享等細項。   2.瞭解競爭對手的活動內容：找出在社群平台上當前的競爭對手是誰？確認後，就可以做出比較，經常查看自己的努力是否符合競爭條件，包括在社群媒體上有多少追隨者？是否頻繁地張貼或更新內容？那些共享的內容最受矚目？   3.評量哪個社群平台比較符合活動需求？現有的社群平台能否接觸到更多的現有客戶或潛在客戶，初期不要浪費時間投資在多種平台上，考量活動比較適合哪個平台。例如，B2B 行銷活動或許採用LinkedIn更有效，而不一定是 Facebook。 4.創造獨特和有趣的內容：共享的內容可以有多種形式，正確的內容類型和格式可以成為貴公司的聲音，展現公司的獨特個性。使用訊息圖表或視頻哪個更能吸引潛在客戶？不管是什麼內容，都需要調整為滿足目標觀眾的需要和興趣。創建社群媒體編輯日曆，確保張貼頻率的一致性。 5.負責成員是誰？應該做些什麼？社群行銷的最大的問題是，誰應該負責內容創建和發布，有沒有行銷或業務部門的人員參與？若內容來自整個公司，專職人員應該負責分配、整理和管理，就必須清楚誰應該負責些什麼？何時需向大家匯報？如果無凝聚力可能弊大於利。 6.選擇平台創建內容都需要目標：邁向成功之路需要哪些指標？目標是否能夠得到滿足？透過審視和衡量目標的效益，找出困難分享成功經驗，使社群媒體策略可以得到加強和鞏固。密切關注新興的平台和內容類型，可以確保社群媒體活動都符合當前客戶的期望。例如，即時行銷有增加的趨勢，需使用數據和技術在短暫的時期內執行它，就需要動員更多的支援人力和物力。

## 內容行銷

美國內容行銷學會(Content Marketing Institute, CMI)將內容行銷定義為一種戰略性的行銷方法，目的在創作和傳播有價值、相關性與一貫性的內容，以吸引並維繫精準的受眾，最終改變或強化目標群行為，帶來商業收入。

內容行銷可視為驅動所有數位傳播「engagement 」的燃料，從搜尋到社群、email行銷，再到創造能夠轉換的網站體驗。

在這樣的大環境下，以消費者需求為核心的內容行銷日益受到重視。本專題將分兩期從「SEO整合」、「AI技術與客製化」、「UGC用戶生成內容」三個面向淺談未來內容行銷因應趨勢，探討內容行銷帶來長期附加價值，並分享相關案例。


內容行銷與SEO本是同根生 好的內容需要SEO技術支援，為內容作優化，將其行銷威力和潛在利益最大化。SEO可以幫助廣告主進一步了解消費者內心的意圖，以發想內容策略。根據BrightEdge研究，內容優化可確保消費者主動搜尋接觸到廣告主提供的內容，這種搜尋佔所有網站流量的51%。對於如何結合內容行銷與SEO，可思考以下三步驟：

編製內容前同時導入SEO技術 在初期就做好SEO整合，將能夠在之後獲得較完整清晰的成果。規劃內容發佈之後才進行優化，不僅可能需要投入更多資源，而且將可能無法獲得預期的效益。
嘗試創建客製化的微型內容 精簡、客製化的內容元素相較長篇、重磅內容更容易針對特定消費者搜尋或問題高度優化，像是網路座談、研究報告、案例解析。 以數據分析驅動內容優化 停止投資對於品牌效益低的內容，轉將資源投入優化其他表現更好的內容。請以20/80法則來思考，重複持續這樣的觀察與投入，廣告主將會看到一些不一樣的成果。  

IKEA以「101種人際關係」佈局搜尋內容 IKEA的「Where Life Happens」系列廣告，找出過去用來填補空間的傢俱在生活中扮演的特別角色，以此回應消費者在網路上求解答的人際關係問題，獲得2017坎城廣告節銅獅獎肯定。 當煩惱的女友搜尋「他都不說愛我」，會找到IKEA黑色留言板、當妻子打出「老公總是在沙發上睡著」，會出現IKEA的板凳…這是因為在宣傳活動期間更改了101項產品名稱，分別對應101種人際關係問題，當消費者搜尋和這些問題有關的關鍵字時，就會出現對應的產品廣告並導向購物網站。 搜尋結果雖無法真正解決消費者的問題，但或許能讓消費者會心一笑。內容和SEO在這次行銷活動中相輔相成，以消費者搜尋的需求發想，客製網站與文案內容；不過由於是單一行銷活動，因此較難看出依據數據長期優化的效果。

人工智慧加速內容產製，開啟個人化行銷機會 行銷自動化整合人工智慧（AI）技術將能達到事半功倍的效果，根據顧問公司Demand Metric統計，80%行銷人員認為遞送個人化內容比對所有人發送一致的內容更有效。AI在內容行銷方面相關的應用大致有以下三個層次： 高效率內容產製 自然語言生成有機會在未來幫助品牌更有效率地產製內容，像是韓聯社已在英超、冬奧期間利用機器人做賽事報導；品牌有機會利用AI工具協助自動生成email、客製化報告或訊息、社群內容。 通訊平台chatbot開發、內容優化 如同先前在凱絡週報專題「社群經營者的第一堂課（下）」中提到的，聊天機器人是近期品牌接觸消費者的熱門工具，透過縝密的內容與行銷活動規劃，提供消費者需要的服務與資訊，聊天機器人能夠整合消費者的位置、需求、和內容互動的模式，據此推送更適切的個人化內容，或獲得下次行銷活動的靈感。 個人化內容策展 例如在品牌經營email或電子報行銷時，演算法可以比對每一位訂閱者的網站造訪紀錄和email互動數據，整合時下熱門話題等等，投遞專屬郵件內容。  

Sephora彩妝測驗、Ada醫生，客製聊天內容 美妝連鎖店Sephora透過Kik（美加流行，月活躍用戶約2.75億）聊天機器人接觸其主要消費者：忙碌的女生族群。Sephora chatbot首先向消費者投遞化妝偏好小測驗，並依據收集到的資訊做個人化產品推薦。用戶將收到產品評論、視頻教學和美容技巧等資訊，可在app內購買產品。 德國人工智慧公司Ada Health開發AI醫生「Ada」，導入大量醫療資訊、數據及AI演算法，能與用戶透過聊天問診。Ada基於用戶提問及與AI的即時對談內容，對健康狀況進行評估，生成一份含有多種可能病因的報告，並說明了病症與病因的關聯性，以及可參考的治療方法，最後提供用戶所在位置附近的醫生資訊，這份報告也能在用戶找專業醫師看診時派上用場。 Facebook近來因用戶個資遭濫用，暫停新的chatbot建置，未來是否影響整體數據產業規則還有待觀察。而在內容行銷過程中導入消費者數據，除了個資保護外，最重要的還是品牌是否能夠提供與消費者真正相關的訊息或服務，改善消費者體驗。

預測客戶流失行為，維繫顧客關係 除了精確掌握目標族群需求，AI和機器學習還能夠進行客戶流失預測。透過AI工具分析目標族群，建立預測模型，並對真實客戶的模型進行測試和驗證，能夠及早發現目標族群在什麼階段可能對品牌產生變動行為，有助品牌應對，降低客戶流失，提高用戶參與。 對於開始使用後很快會棄用的消費者（quick-chur），品牌不易和他們重新開啟互動；但對於和品牌有長期關係的客群（late-churn），可以在他們使用時間縮短等「流失」指標出現時，投遞優惠、信件等內容，提高消費者參與度。 新創公司Vidora提供許多傳媒巨頭如華爾街日報、日本Yahoo和沃爾瑪旗下的Vudu視頻服務等媒體公司AI服務。其系統能夠學習推薦內容，包括影音內容，並可以針對每一位用戶找到最佳的價格與價值主張，當訂閱服務出現時，也能夠根據用戶數據決定要購入哪些劇集。

YouTube兩道過濾器，打造專屬推薦清單 全球用戶每天在YouTube平台上觀看時數突破10億小時，其中七成來自推薦影片。YouTube的客製化影片推薦演算法以用戶觀看歷史、搜尋紀錄以及用戶的統計訊息，掌握用戶當下真正的需求或是有興趣的內容，提升用戶停留在YouTube平台的時間。 YouTube推薦系統主要是以兩個神經網絡組成：一、生成候選影音，二、生成對應的排名。深度協同過濾可以有效的吸收多種信號，通過深層網絡對信號間的相互作用建模學習。 第一個過濾器是候選生成器，主要蒐集用戶在YouTube的觀看歷史與觀看時間，同時考慮相似用戶的瀏覽紀錄，因此如果某個視頻能從數百個之中脫穎而出成為你的候選影片，必定與你的觀看紀錄有關，同時還有一個跟你相似的用戶已經看過它。 第二個過濾器生成排名器，主要是基於用戶輸入的因素，及影片的新鮮程度和點擊率等。

UGC成本低、擴散快，影音形式潛力無窮 用戶生成內容（UGC）對於行銷人員來說，是花更少的成本、產出更豐富的內容，達到更好的傳播效果。  UGC透過核心客群展現對品牌的忠誠度，和行銷活動產生連結，建立大眾對品牌的信任感，持續產出對其他消費者有價值、有意義的內容。在電商網站內置入網友生成的內容，不但能提升網站人氣、建立顧客信心，還有長尾導購及SEO的效果。 93%的消費者（尤其是千禧世代），認為UGC提供了購買決策時的重要參考依 據。 ─美國內容行銷學會（CMI） MAVRCK去年的報告發現，用戶發佈原創內容的篇數呈現下滑的趨勢。除了贈獎外， 品牌還能如何激勵消費者參與內容募集甚至自動產出？UGC主要借用了人 們「愛秀」的心理，觀察目前案例多數有一、知名品牌募集；二、設計挑戰讓 消費者發揮創意；三、募集對他人有幫助的內容等要素。 2016年Facebook上的用戶生成內容參與 度是品牌發佈內容的 6.9倍。 ─市調公司MAVRCK 根據尼爾森，查詢各類資訊和數位影音觀看是目前網友第三、第四大網路用途，「素人／個人上傳影音」在 2017上半年成為最多人在網路上收看的影音類型。推測影音將是最受歡 迎的用戶生成內容形式。 

自己的杯子自己畫，星巴克21天募集4,000個塗鴉杯 2014年星巴克舉辦White Cup Contest杯子塗鴉賽，鼓勵消費者使用自己獨一無二的環保紙杯：要價一美元，可以重複使用。網路上本就有熱愛塗鴉的消費者不時分享自己隨手畫的杯子，開開星巴克logo的玩笑，因此星巴克這次只是透過一個競賽，鼓勵網友創作以募集大量內容，21天獲得4,000件作品。 White Cup Contest利用各社群平台的特性，整合最大綜效。透過專門收集顧客意見的網站MyStarbucks Idea和Facebook發佈活動辦法、炒熱氣氛，競賽機制則要求參加者必須追蹤、上傳作品到Instagram或Twitter，最後利用適合呈現大量瀑布流圖像的Pinterest發佈募集到的內容。 「競賽遊戲」是激發顧客創造內容的極佳方式，但挑戰性、新奇感不可或缺。White Cup Contest發覺消費者想要專屬紙杯的心理，挖掘了許多民間手繪神人為星巴克做免費宣傳，讓「紙杯塗鴉」不僅止於單一行銷活動，而慢慢形成一種文化，如2016年聖誕杯設計選自1,200名民間設計師的作品，2017年則將外帶杯設計成可供消費者填色的著色本。

從網路梗圖到實體展覽，Cheetos銷量破紀錄 起司零食奇多（Cheetos）每條形狀都不一樣，因為生產過程中餅乾內含的水蒸氣接觸空氣膨脹後， 產生的形變是隨機的。利用這樣的產品特性，奇多推出一系列Cheetos Museum活動，邀請網友邊吃邊看，只要發現長相獨特的奇多，幫他命名、拍照上傳，就有機會獲得5,000美金，每週選出兩位幸運兒。 網路梗圖蔚為風潮，網友發揮搞怪精神，找出長得像川普、自由女神的Cheetos都不奇怪，甚至有網友轉到eBay上拍賣，一條像猩猩的Cheetos，竟以10萬美元高價售出，即使可能是暗樁，仍引來媒體爭相報導。

長期經營好內容，培養忠誠客為品牌發聲 前面提到的「SEO」、「AI與客製化」、「用戶生成內容」都是當前品牌在考慮內容行銷時應該一起納入規劃中的幾個元素，不管如何搭配使用，未來內容行銷的核心都在「整合」，包括整合多種技術、整合不同來源的數據、整合利用各平台的特性等等。 內容行銷不以銷售為前提，但最終還是要達到銷售目的。不追求在內容中帶到產品或品牌，而是透過長期的關係經營，給予有價值的資訊，深化消費者購買產品的原因。因此，除了一般的消費指標（如影片瀏覽數／觀看完整度）、互動指標（按讚／分享／討論）等短期目標外，也要考量到長期指標，例如品牌好感度、忠誠度的提升、潛在客群的挖掘與開發，並持續觀察在長期是否有創造利益。 內容行銷通常不會比其他行銷技術更快或更便宜，也不能替代其他行銷方式，而是幫助其他行銷方式獲得更好的成果，培養更好、更忠誠、願意與他人分享品牌故事的顧客，打造品牌重要的戰略資產。

長期經營好內容，培養忠誠客為品牌發聲 前面提到的「SEO」、「AI與客製化」、「用戶生成內容」都是當前品牌在考慮內容行銷時應該一起納入規劃中的幾個元素，不管如何搭配使用，未來內容行銷的核心都在「整合」，包括整合多種技術、整合不同來源的數據、整合利用各平台的特性等等。 內容行銷不以銷售為前提，但最終還是要達到銷售目的。不追求在內容中帶到產品或品牌，而是透過長期的關係經營，給予有價值的資訊，深化消費者購買產品的原因。因此，除了一般的消費指標（如影片瀏覽數／觀看完整度）、互動指標（按讚／分享／討論）等短期目標外，也要考量到長期指標，例如品牌好感度、忠誠度的提升、潛在客群的挖掘與開發，並持續觀察在長期是否有創造利益。 內容行銷通常不會比其他行銷技術更快或更便宜，也不能替代其他行銷方式，而是幫助其他行銷方式獲得更好的成果，培養更好、更忠誠、願意與他人分享品牌故事的顧客，打造品牌重要的戰略資產。 創造銷售以外的附加價值 內容行銷旨在透過長期經營品牌內容，進而達到銷售目的；但長期經營的結果，不只反映在產品的銷售數字上，更因累積了大量的原創內容，增加了內容授權、媒體廣告等永久附加價值。 Red Bull是把內容行銷經營成媒體帝國的知名案例。2005成立Red Bull F1車隊、贊助多項運動賽事，到後來成立「Red Bulletin雜誌」、「Red Bull Records唱片公司」以及簽約藝人和樂團。背後是Red Bull Media House媒體集團整合，並發展Red Bull TV等專屬頻道，長期用豐富有趣的內容，堆積出品牌精隨「Red Bull Gives You Wings」。 從內容產出到內容推廣， Red Bull長期的自產自銷策略，成功讓品牌握有溝通訊息的精準度與掌控權，並在媒體圈建立良好口碑，甚至擁有穩定死忠的收視群，就連像是汽車品牌、球鞋品牌等都爭相購買Red Bull品牌自媒體的廣告，開闢新的商業模式。

LV七年經營NOWNESS平台，緊握時尚話語權 隸屬於全球第一精品集團LVMH的國際文化線上平台，NOWNESS匯聚全世界的藝術、時尚、設計、 美食、旅遊各項頻道，每日呈現獨家的內容。可說在時尚影藝的世界裡，NOWNESS被人們視為不容質疑指標與金字招牌。 許多品牌都說要做內容，但通常仍停留在品牌自說自話。然而NOWNESS平台上面產出的內容，並不單是流行跟風、假文青模仿，而是扎扎實實的創作！他們致力與藝術家們合作，產出非常具實驗性、走在時代前端的內容，且不避談競品，連續七年、天天更新。 消費者對於購買決策的考量，通常是朋友推薦的優先、再來是專家與網友評價，最後才是品牌與廣告。以Louis Vuitton的品牌定位來說，無法做每個消費者的朋友，因此他們致力做業界的專家。 專業大師形象塑造，是依據品牌的長期表現，與來自各界許多專家的背書。NOWNESS的美感與風格建立並非一蹴可幾：擁有七年歷史，連續四年威比獎、柏林時裝電影節最佳視覺效果，拿下的豐富獎項足以證明其權威與影響力。

結語 「內容行銷」是不斷產出高價值、與顧客高度相關的內容來吸引目標客群關注；避免直接討論產品或服務，真正為消費者解決問題，以「改變顧客行為或消費習慣為目的」，最終使得顧客對企業產生信賴和忠誠感，進而產生更多行動力。 內容行銷相對比廣告有更長的時效性。傳統廣告會在特定時間、特定渠道出現，而且出現時須按觀眾或讀者人數付費；內容則幫助品牌實現Always-on，它不再是曇花一現的活動爆發，而是持續的傳播與參與。 長期內容產出與自媒體經營，讓品牌更能掌握消費者訊息與媒體平台資源，帶來更高的流量以及轉換變現率，獲得額外收益與附加價值。 在此提醒廣告主在規劃內容行銷之前，請務必回歸檢視品牌真正面臨的問題、不同品牌類別的差異化市場特性等，以做整合佈局，藉此拿到具有意義的顧客資料，結合數據的驅動，進行洞察受眾、創建策略與內容、精準推廣與溝通、評估內容，讓內容數據產生「複利」，累積成為品牌資產。 內容行銷通常不會比其他營銷技術更快、更便宜或更有效率將客戶轉移到渠道上；但是其更大的力量 在於能夠生成更忠誠的顧客，或更願意與他人分享他的故事的顧客，帶動更高品牌價值的傳播。

## 討論 {-}

## 作業 {-}
