# 網路行銷規劃{#internet-marketing-planning}

行銷規劃是企業發展行銷策略的藍圖，可以引導企業分配資源，在關鍵時刻做出決策。在有限的資源下，企業需要透過規劃，進行分析、計畫、執行與控制，以產生、建立並維繫與目標對象

Kotler認為行銷規劃程序可分為四個階段：

1. 分析市場機會與消費者行為
2. 研究並選擇目標市場
3. 發展並擬定行銷組合策略
4. 行銷活動之組織、執行與控制

因為網路行銷更重視顧客角度與科技的應用，Mohammed等人建議，除了上述的四個階段外，還需要增加三個部分：設計顧客經驗、規劃與設計顧客介面及善用科技整合顧客資料。以下分別說明這七個階段。

## 分析市場機會與消費者行為

為了掌握現有的市場機會或創造新的市場機會，行銷管理的第一個階段便是有系統且定期分析各種市場環境與消費者行為。市場環境整體包括總體環境與個體環境。

總體環境是指企業無法控制，但會對企業帶來威脅與機會的外在環境力量，包括人口因素、經濟、科技、政治法律以及社會文化等外在環境的改變。

行銷的個體環境由所有協助或影響企業產銷活動的個人、群體或組織構成，包括顧客、供應商、行銷中間機構和競爭者。

## 研究並選擇目標市場

經過分析市場機會後，便對該市場機會中，選擇最有利的市場區隔，集中資源與火力，強攻下該市場區隔。所謂**市場區隔(market segmentation)**便是指利用適當的區隔變數(如人口變項、地理、心理和行為等等)，將市場區隔成若干細分的市場。

在選擇好市場區隔後，行銷人員必須為商品在市場上找尋最佳的**定位(positioning)**，強調商品特色，突顯商品與眾不同。行銷人員可以根據商品屬性、用途、使用時機、品質、價格、競爭者以及使用這特性等決定定位。

## 設計與管理顧客經驗

研究證實網站訪客對網站的忠誠度決定於其是否有良好的使用經驗。使用者在網站上的使用經驗，大致可分為四個階段：

- 功能性階段：考慮網站對自己的實用性
  - 可用的(usable)
  - 容易導覽(easy navigation)
  - 快速(speedy)
  - 可靠的(reliable)
- 親密性階段：考慮網站對自己的意義
  - 高度信任
  - 一致的使用經驗與品牌訊息
  - 快速而有效的溝通
  - 高度個人化與獨特價值
- 內化階段：
  - 有價值
  - 生活的一部份
- 代言階段：
  - 為產品宣傳
  - 為產品辯護

## 規劃與設計顧客介面

網站是電子商務關鍵的接觸點，因此顧客介面的設計相當重要，其重點在於：

- 介面給予顧客的機能與美感等感受
- 網站上提供的商品、服務與資訊等內容以及與其他網站相連的連結
- 連結顧客與上下游廠商的社群，利用網路與顧客保持溝通
- 由企業發起，為不同顧客訂做的個人化，或由顧客發起並管理的客製化
- 促進商業交易，支援其價值主張與商業模式

## 擬定網路行銷行動計畫

為了以更寬廣、更詳盡的眼光審視市場和企業狀況，充分運用與活絡既有資產與獨特能力，請楚地描繪目標顧客輪廓，有效地分配資源，企業在進行網路行銷前需要擬定行動計畫，也就是以書面方式詳細說明執行行銷策略時所需的「資源」、「人力」和「時間點」：

1. 要採取什麼行動
2. 何時採取行動
3. 由誰負責執行

## 善用科技整合顧客資料

網路行銷模式的建構，包含以下步驟

1. 將蒐集到的顧客資料，建立資料庫。
2. 依據顧客特性，區分成多個顧客群。
3. 針對不同顧客群，開發新的數位產品或服務。
4. 以有用、娛樂或創新等特性，對每一種數位產品或服務進行促銷，以吸引顧客注意。
5. 透過數位工具與顧客溝通。

綜合以上所述，數位時代的行銷特色是以資料庫為核心，依據蒐集的顧客資料區分為數個顧客群，再就各顧客群的特性，選擇合適的行銷策略。

## 評估網路方案執行成效

評估各種網路行銷策略的選擇與計畫執行是否符合企業整體策略與目標。

## 討論 {-}

## 作業 {-}
