# 網路行銷組合{#internet-marketing-mix}

企業要滿足顧客，實現經營目標，不能孤立地只是考慮某一因素和手段，必須從目標市場需求和市場行銷環境的特點出發，根據企業的資源和優勢，綜合運用各種市場行銷手段形成統一的、配套的市場行銷戰略，使之發揮整體效應，爭取最佳效果，這就是所謂**行銷組合**。傳統的行銷組合一般可分為四大項，稱為4P策略。網路時代顧客關係行銷的思維興起，網路行銷策略從消費者需求的角度來看就需要4C策略。本次課程將說明傳統行銷的4P組合策略與網路行銷的4C組合策略。



## 傳統行銷的4P組合策略

美國密西根州立大學教授─麥卡錫(McCarthy) 在1960年提出行銷4P組合策略，這個架構認為企業應在**做好市場調查的基礎上**，生產出質量好的能夠賣得出去的產品 (product)，制定合理價格 (price)，注重經銷商的培育和銷售通路的建立 (地點， place)，通過一定的推廣手段(promotion)實現交易去達成企業的行銷目標。

1. Product產品：注重開發的功能，要求產品有獨特的賣點，把產品的功能訴求放在第一位。

2. Price價格：是消費者願意支付產品的費用。調整價格對於市場策略有深刻的影響，根據不同的市場定位，制定不同的價格策略，產品的定價依據是企業的品牌戰略。

Place通路：
將產品從生產者 （製造者／供應商） 移轉到消費者或使用者的組織或企業，也就是消費者或使用者購買或取得產品或服務的管道。

Promotion推廣：
代表各種市場行銷者使用的溝通方式，可以讓不同的群體可以了解產品。促銷一般包括：廣告，公共關係，人員銷售…等等。

4P行銷理論，該理論認為。行銷4P一直以來廣被全球的學術界與行銷人員採用，且歷久不衰，為行銷管理的基石。
4P理論的偉大在於把行銷簡化並便於記憶和傳播，促進了市場行銷理論的普及和應用。當然，對於專業人士而言，它的簡單也正是它的不足，4P是研究製造業中消費者的行銷活動時所發明的，在製造業中較為適用，但是他無法涵蓋所有的行銷變數，一但出了製造業的範疇，4P理論可能就不太適用。

企管大師傑洛姆．麥卡錫（Jerome McCarthy），在 1960 年提出強化企業行銷力的「行銷4P 組合策略」：

他認為成功且完整的行銷專案，包含生產適當的產品、訂定適當的價格、決定可行的通路系統，和適當的促銷手段。 許多品牌經營者在擬定市場行銷策略時，4P 行銷理論成為企劃案重要的基礎和依據，可見這個理論有多麼深遠的影響。

產品的組合：主要包括產品的實體、服務、品牌、包裝。它是指企業提供給目標市場的貨物、服務的集合 包括產品的效用、質量、外觀、樣式、品牌、包裝和規格，還包括服務和保固等因素。

價格的組合：主要包括基本價格、折扣價格、付款時間、借貸條件等。它是指企業出售產品所追求的經濟回報。

地點通常稱為分銷的組合：它主要包括分銷管道、儲存設施、運輸設施、存貨控制，它代表企業為使其產品進入和達到目標市場所組織、實施的各種活動，包括途徑、環節、場所、倉儲和運輸等。

促銷組合：是指企業利用各種資訊載體與目標市場進行溝通的傳播活動，包括廣告、人員推銷、營業推廣與公共關係等等。以上4P ( 產品、價格、地點、促銷) 是市場行銷過程中可以控制的因素 也是企業進行市場行銷活動的主要手段 對它們的具體運用，形成了企業的市場行銷戰略。

從4P 的組合特點分析:
(1) 具有可控性。構成市場行銷組合的各種手段，是企業可以調節、控制和運用的因素，如企業根據目標市場情況，能夠自主決定生產什麼產品、制定什麼價格、選擇什麼銷售管道、採用什麼促銷方式。

(2) 動態性。市場行銷組合不是固定不變的靜態組合而是變化無窮的動態組合。企業受到內部條件、外部環境變化的影響，必須能主動地做出相應的反應。

(3) 具有整體性。市場行銷組合的各種手段及組成因素，不是簡單的相加或拼湊集合，而應成為一個有機的整體，在統一目標指導下，彼此配合、相互補充，能夠求得大於局部功能之和的整體效應。

## 網路行銷的4C策略

隨著時代的演變，市場從製造導向慢慢轉為全面消費者導向，於是後來衍伸出著中在消費者的「4C」。

上述傳統的行銷4P，是從生產者觀點出發的行銷觀點。隨著市場競爭逐漸激烈、消費者意識抬頭，品牌行銷策略逐漸轉為消費者導向。 行銷專家羅伯特．勞特朋（Robert F. Lauterborn）在1990年提出以消費者需求為中心的 4C 理論：
Customer 顧客：
企業必須首先了解和研究顧客，根據顧客的需求來提供產品。同時，企業提供的不僅僅是產品和服務，更重要的是由此產生的客戶價值 (Customer Value)。
Cost 成本：
不單是企業的生產成本，或者說4P中的Price( 價格 ),它還包括顧客的購買成本，同時也意味著產品定價的理想情況，應該是既低於顧客的心理價格，亦能夠讓企業有所盈利。此外，這中間的顧客購買成本不僅包括其貨幣支出，還包括其為此耗費的時間，體力和精力消耗，以及購買風險。
Convenience 便利：
指購買的方便性( Convenience to buy) 。比之傳統的行銷管道 新的觀念更重視服務環節在銷售過程中，強調為顧客提供方便性，讓顧客既購買到商品也購買到方便性。
Communication 溝通：
企業應通過同顧客進行積極有效的雙向溝通，建立基於共同利益的新型企業/ 顧客關係。這不再是企業單向的促銷和勸導顧客，而是在雙方的溝通中找到能同時實現各自目標的通途。
不過當然，4C理論也有其不足的地方，它以顧客需求為導向，但顧客需求有個合理性問題，如果企業只是被動適用顧客的需求，必然會付出巨大的成本，根據市場的發展，應該尋求在企業與顧客之間建立一種更主動的關係；4C雖然是以顧客為中心進行行銷，但卻沒能體現既贏得客群，又長期地擁有客群的關係行銷思想，沒有解決滿足顧客需求的操作性問題。

隨著市場競爭逐漸激烈、消費者意識抬頭，品牌行銷策略逐漸轉為消費者導向。 其中， 行銷專家羅伯特． 勞特朋（ Robert F. Lauterborn ） 在 1990 年提出以消費者需求為中心的 4C 理論

Consumer 消費者需求
Cost 消費者購買商品的成本
Convenience 消費者的便利性
Communication 如何和消費者溝通
他強調品牌經營者應該生產符合顧客需要的產品、以顧客願意付出的成本來訂價格、通路要考量顧客購物的便利性，以及提供顧客雙向溝通的管道。

行銷學家菲利普˙科特勒認為，企業所有部門為服務於顧客利益而共同工作時，其結果就是整合行銷。其意義就是強調各種要素之間的關聯性要求它們成為統一的有機體。具體地講，整合行銷更要求各種行銷要素的作用力統一方向，形成合力，共同為企業的行銷目標服務。4C的行銷觀念: 4C分別是: 消費者( consumer) 、成本( cost) 、方便性( convenience) 、溝通( communication) 。4C強化了以消費者需求為中心的行銷組合，其內涵與應用是：

(1) 消費者(consumer)：指消費者的需要和慾望( The needs and wants of consumer) 。企業要把重視顧客放在第一位 強調創造顧客比開發產品更重要 滿足消費者的需求和慾望比產品功能更重要 不能僅僅賣企業想製造的產品 而是要提供顧客確實想買的產品。

(2) 成本(cost)：指消費者獲得滿足的成本( Cost and value to satisfy consumer needs and wants) 或是消費者滿足自己的需要和慾望所肯付出的成本價格。這裡的行銷價格因素延伸為生產經營過程的全部成本。包括: 企業的生產成本即生產適合消費者需要的產品成本；消費者購物成本，不僅指購物的貨幣支出還有時間耗費、體力和精力耗費以及風險承擔。新的定價模式要求: 消費者支持的價格 — 適當的利潤 = 成本上限。因此企業要想在消費者支持的價格限度內增加利潤，就必須降低成本。

(3) 方便性(convenience)：指購買的方便性( Convenience to buy) 。比之傳統的行銷管道 新的觀念更重視服務環節在銷售過程中，強調為顧客提供方便性，讓顧客既購買到商品也購買到方便性。企業要深入瞭解不同的消費者有哪些不同的購買方式和偏好，把方便性原則貫穿於行銷活動的全過程。售前做好服務及時向消費者提供關於產品的性能、質量、價格、使用方法和效果的準確資訊，售後應重視資訊反饋和追蹤調查，及時處理和答覆顧客意見對有問題的商品主動退換，對使用故障積極提供維修方便，大件商品甚至終身保修。

(4) 溝通(communication)：指與用戶溝通( Communication with consumer)。企業可以嘗試多種行銷策劃與行銷組合，如果未能收到理想的效果，說明企業與產品尚未完全被消費者接受。這時，不能依靠加強單向勸導顧，要著眼於加強雙向溝通，增進相互的理解，實現真正的適銷對路，培養忠誠的顧客。

## 討論 {-}

## 作業 {-}
