# 顧客流失分析 {#customer-churn-analysis}

(https://towardsdatascience.com/predict-customer-churn-with-r-9e62357d47b4)

載入套件
```{r}
library(tidyverse)
library(lubridate)
library(readxl)
```

讀取資料集檔案[線上零售資料集](https://archive.ics.uci.edu/ml/datasets/Online+Retail)
```{r}
Online_Retail <- read_excel("Online Retail.xlsx")
```

檢視資料集，這是一個發票的檔案，包含發票編號(InvoiceNo)、貨品編號(StockCode)、描述(Description)、數量(Quantity)、發票日期(InvoiceDate)、單價(UnitPrice)、顧客識別號(CustomerID)、國別(Country)等變數欄位。
```{r}
summary(Online_Retail)
```

計算每一筆紀錄的消費金額(數量*單價)
```{r}
Online_Retail <- Online_Retail %>%
  mutate(Total=Quantity*UnitPrice)
```

計算每一個顧客每一天每一張發票上的消費金額總數
```{r}
txns <- Online_Retail %>% 
  group_by(CustomerID, InvoiceNo, InvoiceDate) %>% 
  summarise(Spend = sum(Total)) %>%
  ungroup() %>% 
  filter(Spend>0) #去除退貨資料，保留購物資料
```

每一個顧客前後筆購物資料時間差距
```{r}
time_between <- txns %>% 
  arrange(CustomerID, InvoiceDate) %>% 
  group_by(CustomerID) %>% 
  mutate(dt = as.numeric(InvoiceDate - lag(InvoiceDate), unit=  'days')) %>% 
  ungroup() %>% 
  filter(!is.na(dt))
```

購買紀錄大於20筆的顧客資料
```{r}
Ntrans <- txns %>% 
  group_by(CustomerID) %>% 
  summarise(N = n()) %>%
  filter(N>20)
```

```{r}
ecdf_df <- time_between %>%
  group_by(CustomerID) %>%
  arrange(dt) %>%
  mutate(e_cdf = 1:length(dt)/length(dt))
```

