# 購物籃分析 {market-basket-analysis}

https://towardsdatascience.com/a-gentle-introduction-on-market-basket-analysis-association-rules-fa4b986a40ce

載入套件
```{r}
library(tidyverse)
library(lubridate) #處理時間資料
library(readxl) #讀取excel檔案
library(arules)
library(arulesViz)
```

讀取資料集檔案[線上零售資料集](https://archive.ics.uci.edu/ml/datasets/Online+Retail)
```{r}
Online_Retail <- read_excel("Online Retail.xlsx")
```

檔案中包含發票編號(InvoiceNo)、貨品編號(StockCode)、描述(Description)、數量(Quantity)、發票日期(InvoiceDate)、單價(UnitPrice)、顧

首先，去除顧客識別號(CustomerID)資料中的NA(Not-Available)，保留非NA的資料，然後再選取發票日期(InvoiceDate)在2010-12-09到2011-12-09之間的資料。
```{r}
Online_Retail <- Online_Retail %>%
  filter(!is.na(CustomerID)) %>% #去除去除顧客識別號中的NA
  filter(InvoiceDate>=as.POSIXct("2010-12-09")) #選取2010-12-09到2011-12-09之間的資料
```

```{r}
Online_Retail <- Online_Retail %>%
  mutate(Date=as.Date(InvoiceDate))
```

```{r}
Online_Retail <- Online_Retail %>%
  filter(!grepl("C", InvoiceNo))
```

```{r}
PurchaseItem <- Online_Retail %>%
  group_by(CustomerID, Date) %>%
  summarise(itemList=paste(Description, collapse = ","))
```

